apiVersion: v1
kind: Service
metadata:
  name: plant-disease-classification-service
spec:
  selector:
    app: plant-disease-classification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
