apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: plant-disease-classification-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       plant-disease-classification-deployment
  updatePolicy:
    updateMode: "Auto"
